sudo apt-get update;
sudo apt-get install npm;
sudo npm install n -g;
sudo n lts;
sudo npm install yarn -g;
npm install;
cd ../;
sh -ci "$(curl -fsSL https://smartcontracts.org/install.sh)";
echo 'export PATH="$PATH:$HOME/bin"' >> "$HOME/.bashrc";
. "$HOME/.bashrc";
sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh;
source $HOME/.cargo/env;
rustup target add wasm32-unknown-unknown;
sudo apt-get install build-essential libssl-dev;
cd /tmp;
wget https://github.com/Kitware/CMake/releases/download/v3.20.0/cmake-3.20.0.tar.gz;
tar -zxvf cmake-3.20.0.tar.gz;
cd cmake-3.20.0;
./bootstrap;
make;
sudo make install;
cmake --version;
cd;
git clone https://github.com/dfinity/internet-identity.git;
cd internet-identity;
npm ci;
cargo install ic-cdk-optimizer --version 0.3.1;
dfx start --background;
II_FETCH_ROOT_KEY=1 II_DUMMY_CAPTCHA=1  dfx deploy --no-wallet --argument '(null)';
cd ../itoka-music-nft-standard
